name: Build and deploy Node.js app to Azure Web App - az-web-training

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        
      - name: Build frontend + backend
        run: npm run build

      - name: Prepare deployment package
        run: |
            mkdir deploy
            cp -r dist server client shared deploy/
            cp package.json package-lock.json deploy/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: az-web-training
          slot-name: Production
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_24E1436B13BE42E499237575D85FA2F2 }}
